version: "3.9"
name: "stock-alertify"

networks:
  internal_nw:
    name: internal_nw
    driver: bridge

services:
  database:
    container_name: database-node
    image: cockroachdb/cockroach:v22.2.0
    command: start-single-node --insecure --http-addr 0.0.0.0
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "26257:26257"
      - "8080:8080"
    networks:
      - internal_nw

  broker:
    image: rabbitmq:3.8-management
    container_name: rabbitmq-node
    hostname: broker
    ports:
      - 0.0.0.0:5672:5672
      - 0.0.0.0:15672:15672
    volumes:
      - "./config/test_setup.sh:/dev/test_setup.sh"
      - "./config/definitions.json:/etc/rabbitmq/definitions.json"
      - "./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_NODE_IP_ADDRESS=0.0.0.0
      - NODE_IP_ADDRESS=0.0.0.0
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit loopback_users "none"
    command: >
      sh -c "rabbitmq-server"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 6
    networks:
      - internal_nw

  fastapi_app:
    build: ../
    container_name: fastapi_app_node
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ../app:/app
    ports:
      - "8005:8000"
    env_file:
      - ../.env
    environment:
      - PYTHONPATH=/code
    depends_on:
      - database
      - broker
    networks:
      - internal_nw

  worker:
    build: ../
    container_name: worker_node
    command: celery -A worker.app.celery_app worker --loglevel=info
    volumes:
      - ../app:/app
    env_file:
      - ../.env
    environment:
      - PYTHONPATH=/code
    depends_on:
      - database
      - broker
    networks:
      - internal_nw

  beat:
    build: ../
    container_name: beat_node
    command: celery -A worker.app.celery_app beat --loglevel=info
    volumes:
      - ../app:/app
    env_file:
      - ../.env
    environment:
      - PYTHONPATH=/code
    depends_on:
      - database
      - broker
    networks:
      - internal_nw

  consumer:
    build: ../
    container_name: consumer_node
    command: python3 event_subscriber/main.py
    tty: true
    volumes:
      - ../app:/app
    env_file:
      - ../.env
    environment:
      - PYTHONPATH=/code
    depends_on:
        broker:
          condition: service_healthy
        database:
          condition: service_started
    networks:
      - internal_nw